[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "NODE_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "PORT"
value = "3001"
